export component CalendarIcon inherits Rectangle {
    in property <color> icon-color;
    width: 20px;
    height: 20px;
    background: transparent;
    Rectangle { x: 2px; y: 3px; width: 16px; height: 15px; border-radius: 3px; border-width: 1px; border-color: root.icon-color; background: transparent; Rectangle { x: 3px; y: 5px; width: 10px; height: 1px; background: root.icon-color; } Rectangle { x: 4px; y: -2px; width: 2px; height: 5px; border-radius: 1px; background: root.icon-color; } Rectangle { x: 10px; y: -2px; width: 2px; height: 5px; border-radius: 1px; background: root.icon-color; } }
}
