export component FolderIcon inherits Rectangle {
    in property <color> icon-color: #ffffff;
    width: 18px;
    height: 15px;
    background: transparent;

    Rectangle { x: 1px; y: 3px; width: 16px; height: 11px; border-radius: 2px; border-width: 1px; border-color: root.icon-color; background: transparent; }
    Rectangle { x: 3px; y: 0px; width: 7px; height: 4px; border-radius: 1px; background: root.icon-color; }
}
