import "../../../ui/fonts/Carlito-Regular.ttf";
import "../../../ui/fonts/Carlito-Bold.ttf";

export { AppWindow, ClockTileData } from "app_window.slint";
export { SettingsWindow, ClockListItem } from "settings_window.slint";
export { AboutWindow } from "about_window.slint";
export { ContextMenuWindow } from "context_menu_window.slint";
export { CalendarWindow, CalendarDayData, CalendarMonthData } from "calendar_window.slint";
export { PlannerWindow } from "planner_window.slint";
export { AlarmAttentionWindow } from "alarm_attention_window.slint";
export { TimerAttentionWindow } from "timer_attention_window.slint";
export { ReminderAttentionWindow } from "reminder_attention_window.slint";
export { EventAttentionWindow } from "event_attention_window.slint";
export { TaskAttentionWindow } from "task_attention_window.slint";
