import { Slider } from "std-widgets.slint";

export component TimeSliderPanel inherits Rectangle {
    in property <[int]> hour-labels;
    in property <float> clock-scale: 1.0;
    in property <length> line-width: 1px;
    in-out property <float> time-step: 0;
    callback request-time-step(float);

    surface := Rectangle {
        width: parent.width;
        height: parent.height;
        clip: true;
        background: root.border-color;

        Rectangle {
            x: root.line-width;
            y: root.line-width;
            width: parent.width - 2 * root.line-width;
            height: parent.height - 2 * root.line-width;
            background: #383838;
            Slider {
                x: 5px * root.clock-scale;
                y: 10px * root.clock-scale;
                width: parent.width - 14px * root.clock-scale;
                height: 28px * root.clock-scale;
                minimum: 0;
                maximum: 288;
                step: 1;
                value <=> root.time-step;
                changed => { root.request-time-step(self.value); }
            }
            for hour[index] in root.hour-labels: Text {
                x: 16px * root.clock-scale + index * (parent.width - 36px * root.clock-scale) / (root.hour-labels.length - 1) - 16px * root.clock-scale;
                y: 41px * root.clock-scale;
                width: 32px * root.clock-scale;
                height: 20px * root.clock-scale;
                text: hour;
                color: #c7c3c3;
                font-size: 12px * root.clock-scale;
                horizontal-alignment: center;
            }
        }
    }
}
